SELECT TOP (1000) [customer_id]
      ,[age]
      ,[gender]
      ,[item_purchased]
      ,[category]
      ,[purchase_amount]
      ,[location]
      ,[size]
      ,[color]
      ,[season]
      ,[review_rating]
      ,[subscription_status]
      ,[shipping_type]
      ,[discount_applied]
      ,[promo_code_used]
      ,[previous_purchases]
      ,[payment_method]
      ,[frequency_of_purchases]
      ,[age_group]
      ,[purchase_frequency_days]
  FROM [customer_behavior].[dbo].[customer_behavior1]

-- Q1. What is the total revenue generated by male vs. female customers? amount?
select gender, SUM(purchase_amount) as revenue
from [customer_behavior].[dbo].[customer_behavior1]
group by gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from [customer_behavior].[dbo].[customer_behavior1]
where discount_applied = 'Yes' and purchase_amount >= (select AVG (purchase_amount) from [customer_behavior].[dbo].[customer_behavior1])

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(AVG(review_rating),2) as "Average Product Rating"
from [customer_behavior].[dbo].[customer_behavior1]
group by item_purchased
order by avg(review_rating) desc 

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, AVG(purchase_amount) as 'Type of Shipping'
from [customer_behavior].[dbo].[customer_behavior1]
where shipping_type in ('Standard','Express')
group by shipping_type

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status, 
count(customer_id) as total_customers,
AVG(purchase_amount) as avg_spend,
SUM(purchase_amount) as total_revenue
from [customer_behavior].[dbo].[customer_behavior1]
group by subscription_status
order by total_revenue, avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, 
100 * SUM(case when discount_applied = 'Yes' then 1 else 0 end)/ count(*) * 100 as discount_rate
from [customer_behavior].[dbo].[customer_behavior1]
group by item_purchased
order by discount_rate desc

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show 
--the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 then 'new'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
	from [customer_behavior].[dbo].[customer_behavior1]
)
select customer_segment, count (*) as "Number of Customers"
from customer_type
group by customer_segment
-- Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
count (customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) DESC) as item_rank
from [customer_behavior].[dbo].[customer_behavior1]
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers
from [customer_behavior].[dbo].[customer_behavior1]
where previous_purchases > 5
group by subscription_status

-- Q10. What is the revenue contribution of each age group?
select age_group, SUM(purchase_amount) as total_revenue
from [customer_behavior].[dbo].[customer_behavior1]
group by age_group
order by total_revenue DESC